web:
  build: .
  command: 'bash -c ''vendor/bin/heroku-php-nginx .'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8081:8080'
shell:
  image: spellchecker_web
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
